"""

Generated by 'django-adm'

in startproject using Django 1.10.

For more information on this file, see

https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see

https://docs.djangoproject.com/en/1.10/ref/settings/

"""



import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = '4e&6aw+(5&cg^_!05r(&7_#dghg_pdgopq(yk)xa^bog7j)^*j'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



ALLOWED_HOSTS = ["127.0.0.1"]





## Application definition



INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'Media_Manager.apps.Accounting',

    #'Media_Manager.apps.Admin',

    'Media_Manager.apps.Advertising',

    'Media_Manager.apps.Circulation',

    'Media_Manager.apps.Editorial',

    'Media_Manager.apps.Home',

    'Media_Manager.apps.Production',
]


#if ADMIN_ENABLED is True:

#   INSTALLED_APPS.append('django.contrib.admin')



MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'Media_Manager.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [

            '/PycharmProjects/testProject/AdBooking/templates/','.', './templates/',

            #['/var/www/Media_Manager/templates', '/var/www/Media_Manager/Media_Manager/', '.', './templates/'],

        ],

        #'DIRS': [os.path.join(BASE_DIR,'templates')],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]






# Database

# https://docs.djangoproject.com/en/1.10/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.mysql',

                'NAME': 'addb',

                'USER': 'root',

                'PASSWORD': '',

                'HOST': 'localhost',

                'PORT': '3306',

        'OPTIONS': {"init_command":"SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED", },

    }

}





# Password validation

# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/1.10/topics/i18n/



LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'UTC'



USE_I18N = True



USE_L10N = True



USE_TZ = True





# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/1.10/howto/static-files/



STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(os.path.dirname(os.path.dirname(__file__)), 'static/')]

#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')